<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompanySeeder extends Seeder {
    public function run() {
        $companies = $this->companies();
    	foreach ($companies as $company) {
	     	DB::table('companies')->insert([
	            'name' 			        => $company['name'],
	            'slug' 			        => Str::slug($company['name']),
	            'logo' 	                => $company['logo'],
                'description'           => $company['description'],
	            'dashboard_type'        => $company['dashboard_type'],
                'upstream_dependencies' => $this->serializeArray($this->properties('upstream_dependencies'), 'ud'),
                'external_dependencies' => $this->serializeArray($this->properties('external_dependencies'), 'ed'),
                'desktop_applications'  => $this->serializeArray($this->properties('desktop_applications'), 'da'),
                'mobile_apps'           => $this->serializeArray($this->properties('mobile_apps'), 'ma'),
                'risk_assets'           => $this->serializeArray($this->properties('risk_assets'), 'ra'),
                'risk_vulnerabilities'  => $this->serializeArray($this->properties('risk_vulnerabilities'), 'rv'),
	            'created_at' 	        => date("Y-m-d H:i:s"),
	            'updated_at' 	        => date("Y-m-d H:i:s"),
	        ]);
    	}
    }
    public function companies() {
        return [
            [
                'name'                  => 'Ontario Pension Board (OPB)',
                'logo'                  => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type'        => 'A', 
                'description'           => '—', 
            ],
            [
                'name'                  => 'Town of Caledon',
                'logo'                  => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type'        => 'A', 
                'description'           => 'Town of Caledon', 
            ],
            [
                'name'                  => 'County of Essex',
                'logo'                  => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type'        => 'B', 
                'description'           => 'County of Essex',
            ],
            [
                'name'                  => 'City of Burlington',
                'logo'                  => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type'        => 'A', 
                'description'           => 'City of Burlington', 
            ],
        ];
    }
    public function companies_all() {
        return [
            [
                'name'           => 'City of Brampton',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => '—', 
            ],
            [
                'name'           => 'City of Burlington',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'City of Burlington', 
            ],
            [
                'name'           => 'City of Guelph',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'City of Guelph', 
            ],
            [
                'name'           => 'City of Oshawa',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'City of Oshawa', 
            ],
            [
                'name'           => 'Clairus Group',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'Clairus Group', 
            ],
            [
                'name'           => 'County of Essex',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'B', 
                'description'    => 'County of Essex', 
            ],
            [
                'name'           => 'Grey County',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'Grey County', 
            ],
            [
                'name'           => 'Haldimand County',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'Haldimand County', 
            ],
            [
                'name'           => 'Hamilton-Wentworth Catholic District School Board',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'Hamilton-Wentworth Catholic District School Board', 
            ],
            [
                'name'           => 'Middlesex County',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'Middlesex County', 
            ],
            [
                'name'           => 'National Bank of Dominica',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'National Bank of Dominica', 
            ],
            [
                'name'           => 'Ontario Pension Board',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'Ontario Pension Board (OPB)', 
            ],
            [
                'name'           => 'SPI Health & Safety',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'SPI Health & Safety', 
            ],
            [
                'name'           => 'Town of Ajax IT Strategy – May 2019',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'Town of Ajax', 
            ],
            [
                'name'           => 'Town of Aurora',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'Town of Aurora', 
            ],
            [
                'name'           => 'Town of Caledon',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'Town of Caledon', 
            ],
            [
                'name'           => 'Town of Halton Hills',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'Town of Halton Hills', 
            ],
            [
                'name'           => 'Town of Innisfil',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'Town of Innisfil', 
            ],
            [
                'name'           => 'Town of Lincoln',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'Town of Lincoln', 
            ],
            [
                'name'           => 'Town of Whitby',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'Town of Whitby', 
            ],
            [
                'name'           => 'Township of South Stormont',
                'logo'           => 'vpwJybakLiCeZuXR4XSWBpIdIAAxrJbZX3y9Jqq3.png', 
                'dashboard_type' => 'A', 
                'description'    => 'Township of South Stormont', 
            ],
            [
                'name'           => 'Demo company to be used for portal testing',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'Vandelay Industries', 
            ],
            [
                'name'           => 'yourtown',
                'logo'           => 'VfHyJJjEgiwXNygblBaAw1AQsjNblikqhziHaHr8.png', 
                'dashboard_type' => 'A', 
                'description'    => 'This is a municipal demo site', 
            ],
        ];
    }
    public function properties($itemId)
    {
        $properties = [
            'upstream_dependencies' => [
                1 => 'Network Access',
                2 => 'Network Access (EMS/OW Private Circuit)',
                3 => 'Network Access (POA Private Circuit)',
                4 => 'Telephony (Phone System)',
                5 => 'Telephony (Cellular)',
                6 => 'Internet/Intranet',
                7 => 'File Services',
                8 => 'Print/Fax Services',
                9 => 'Email',
                10 => 'Remote Access',
                11 => 'ECM (Alfresco)',
                12 => 'Application Service (GIS)',
                13 => 'Application Services (Nurse Call)',
                14 => 'Application Services (Wanderguard)',
                15 => 'Application Services (Great Plains)',
                16 => 'Application Services (POA Dashboard)',
                17 => 'Application Services (Corporate Website)',
                18 => 'Application Services (OCCMS)',
                19 => 'Application Services (SRM)',
                20 => 'Application Services (HRWare)',
                21 => 'Application Services (CAMS)',
                22 => 'Application Services (Siemens BAS)',
                24 => 'Application Services (Inspections Reporting)',
                25 => 'Application Services (Worksheets)',
                26 => 'Application Services (Tweedsmuir Web Service)',
                27 => 'Application Services (Council Expense)',
                29 => 'Application Services (Capital Projects)',
                30 => 'Application Services (Emergency Contacts)',
                31 => 'Application Services (Emergency Management Portal)',
                32 => 'Application Services (Bellamy)',
                23 => 'Database Services (MSSQL)',
                33 => 'Database Services (PostgreSQL)',
                34 => 'Database Services (MariaDB)',
            ],
            'external_dependencies' => [
                1 => 'Activty Pro (SPH)',
                2 => 'Agora Pulse',
                3 => 'Canva',
                4 => 'CCAC-HPG (SPH)',
                5 => 'Clinical Connect',
                6 => 'CIBC Online',
                7 => 'CityWide',
                8 => 'Debit/Credit Machine (EWSWA)',
                9 => 'eHealth (SPH and EMS)',
                10 => 'eSolutions Bids and Tenders',
                11 => 'eSolutions County Connect',
                12 => 'eSolutions Recruit Right',
                13 => 'eSolutions eclaims',
                14 => 'eSolutions Form Builder',
                15 => 'GreenShield',
                16 => 'KnowBe4',
                17 => 'Life Labs',
                18 => 'Meda  Compiance',
                19 => 'Menu Stream',
                20 => 'MESH',
                21 => 'MPAC Municipal Connect',
                22 => 'MOHLCT Enhanced Rate Reduction (E-RRISA)',
                23 => 'MSDSonline',
                24 => 'ONE online (Finance)',
                25 => 'OMERS',
                26 => 'Point Click Care',
                27 => 'Pharmacy (Policy Manager )',
                28 => 'SunLife',
                29 => 'Sysco',
                30 => 'TextNet',
                31 => 'WSIB',
                32 => 'Xirrus',
                33 => 'CIBC CMO',
                34 => 'CIBC PWM',
                35 => 'Moneris',
                36 => 'MTE (Property Taxes)',
                37 => 'Weather Stations (EWSWA)',
                38 => 'HR Downloads (Online Training)',
                39 => 'Harvard Manage Mentor (Online Training)',
                40 => 'Spend Dynamics (BMO)',
                41 => 'Meeting Management (eScribe)',
                42 => 'CIRA (DNS)',
                43 => 'GeoLogic (GCS)',
                44 => 'ArcGIS Online',
                45 => 'SurgeLearning',
            ],
            'desktop_applications'  => [
                1 => 'Email (Microsoft Exchange) + Weblink',
                2 => 'Microsoft Office 2019',
                3 => 'Access Database',
                4 => 'ACT!',
                5 => 'Adobe Pro DC',
                6 => 'Adobe Reader DC',
                7 => 'ADP',
                8 => 'ADP Report Smith',
                9 => 'APC/Liebert Alerting',
                10 => 'AutoCAD Civil3D',
                11 => 'Avigilon Control Center/Cameras',
                12 => 'CAD (EWSWA)',
                13 => 'Clinical Connect',
                14 => 'CODE-STAT',
                15 => 'FitPro',
                16 => 'Geologix (GPS Software)',
                17 => 'GEOWare',
                18 => 'GridSmart',
                19 => 'InfoHR',
                20 => 'Laserfiche + Weblink',
                21 => 'LogMeIn',
                22 => 'MESH',
                23 => 'NexTalk TextNet Client',
                24 => 'PriijectorMMX',
                25 => 'Protege',
                26 => 'Sage 300 Accounting (Accpac)',
                27 => 'Synchro Traffic Software',
                28 => 'TES Map',
                29 => 'TextNet',
                30 => 'Wellspring Print Boss',
                31 => 'Winfuel',
                32 => 'Zoom',
                33 => 'ArcGIS Desktop',
                34 => 'ArcGIS Pro',
                35 => 'GeoCortex Report Designer',
                36 => 'GeoCortex Workflow Designer',
                37 => 'GeoExpress (LizardTech)',
            ],
            'mobile_apps'           => [
                1 => 'Mobile 1',
                2 => 'Mobile 2',
                3 => 'Mobile 3',
                4 => 'Mobile 4',
                5 => 'Mobile 5',
                6 => 'Mobile 6',
                7 => 'Mobile 7',
            ],
            'risk_assets'           => [
                1 => 'B1_BUSINESS PROCESSES_CRITICAL',
                2 => 'B2_BUSINESS PROCESSES_SECRET',
                3 => 'B3_BUSINESS PROCESSES_KEY',
                4 => 'B4_BUSINESS PROCESSES_REGULATORY',
                5 => 'I1_INFORMATION_CONFIDENTIAL',
                6 => 'I2_INFORMATION_RESTRICTED',
                7 => 'I3_INFORMATION_INTERNAL',
                8 => 'I4_INFORMATION_PUBLIC',
                9 => 'I5_INFORMATION_HARDCOPY',
                10 => 'H1_HARDWARE_SERVER',
                11 => 'H2_HARDWARE_WORKSTATION',
                12 => 'H3_HARDWARE_STORAGE',
                13 => 'H4_HARDWARE_MOBILE',
                14 => 'H5_HARDWARE_PERIPHERAL',
                15 => 'S1_SOFTWARE_OS',
                16 => 'S4_SOFTWARE_SUPPORTING',
                17 => 'S2_SOFTWARE_APPLICATION',
                18 => 'S3_SOFTWARE_CUSTOM',
                19 => 'N1_NETWORK_CONNECTIVITY',
                20 => 'N2_NETWORK_DEVICES',
                21 => 'N3_NETWORK_TELEPHONY',
                22 => 'N4_NETWORK_CLOUD',
                23 => 'P1_PERSONNEL_MANAGEMENT',
                24 => 'P2_PERSONNEL_OPERATIONS',
                25 => 'P3_PERSONNEL_DEVELOPERS',
                26 => 'F1_FACILITIES_EXTERNAL',
                27 => 'F2_FACILITIES_PREMISES',
                28 => 'F3_FACILITIES_BRANCH',
                29 => 'F4_FACILITIES_ESSENTIAL',
                30 => 'F5_FACILITIES_COMMUNICATION',
                31 => 'F6_FACILITIES_UTILITIES',
            ],
            'risk_vulnerabilities'  => [
                1 => 'V1_ SENSITIVE DATA_IDENTIFICATION',
                2 => 'V2_SENSITIVE DATA_CLASSIFICATION',
                3 => 'V3_SENSITIVE DATA_PROTECTION',
                4 => 'V4_SENSITIVE DATA_DATA LOSS PREVENTION',
                5 => 'V5_SENSITIVE MEDIA_SANITIZATION',
                6 => 'V6_ CYBERSECURITY_PROGRAM',
                7 => 'V7_ CYBERSECURITY_TRAINING',
                8 => 'V8_CYBERSECURITY_MATURITY',
                9 => 'V9_SECURITY LIFECYCLE_SYSTEM ACCESS',
                10 => 'V10_SECURITY LIFECYCLE_THIRD-PARTY ACCESS',
                11 => 'V11_SECURITY LIFECYCLE_PATCH MANAGEMENT',
                12 => 'V12_SECURITY LIFECYCLE_RESOURCE ALLOCATION',
                13 => 'V13_SERVICE MANAGEMENT_CHANGE MANAGEMENT',
                14 => 'V14_SERVICE MANAGEMENT_INCIDENT MANAGEMENT',
                15 => 'V15_SERVICE MANAGEMENT_PROBLEM MANAGEMENT',
                16 => 'V16_SERVICE MANAGEMENT_KNOWLEDGE MANAGEMENT',
                17 => 'V17_SERVICE MANAGEMENT_ASSET MANAGEMENT',
                18 => 'V18_SYSTEM AND DATA INTEGRITY_HIGH AVAILABILITY',
                19 => 'V19_SYSTEM AND DATA INTEGRITY_ANTI-VIRUS',
                20 => 'V20_SYSTEM AND DATA INTEGRITY_INTRUSION DETECTION',
                21 => 'V21_SYSTEM AND DATA INTEGRITY_SECURITY MANAGEMENT',
                22 => 'V22_NETWORK RESILIENCY_SINGLE POINT OF FAILURE',
                23 => 'V23_NETWORK RESILIENCY_CONTRACT MANAGEMENT',
                24 => 'V24_NETWORK MONITORING_MONITORING',
                25 => 'V25_NETWORK LOGGING & AUDITING_LOGGING AND REPORTING',
                26 => 'V26_NETWORK LOGGING & AUDITING_SCHEDULED REVIEWS',
                27 => 'V27_IDENTIFICATION AND AUTHENTICATION_ACCESS CONTROL',
                28 => 'V28_IDENTIFICATION AND AUTHENTICATION_ACCOUNT REVIEWS',
                29 => 'V29_BUSINESS CONTINUITY AND DISASTER RECOVERY_BACKUP',
                30 => 'V30_BUSINESS CONTINUITY AND DISASTER RECOVERY_PLANNING',
                31 => 'V31_BUSINESS CONTINUITY AND DISASTER RECOVERY_ASSETS',
                32 => 'V32_BUSINESS CONTINUITY AND DISASTER RECOVERY_TESTING',
                33 => 'V33_DATA CENTRE FACILITY_FIRE SUPRESSION',
                34 => 'V34_DATA CENTRE FACILITY_POWER AND COOLING',
                35 => 'V35_DATA CENTRE FACILITY_WATER DAMAGE',
                36 => 'V36_RESOURCE_LOSS OF STAFF',
                37 => 'V37_RESOURCE_CROSS-TRAINING',
                38 => 'V38_CLOUD_USER PROVISIONING',
                39 => 'V39_CLOUD_HYPERVISOR',
                40 => 'V40_CLOUD_POOR KEY MANAGEMENT PROCEDURES',
                41 => 'V41_CLOUD_LACK OF SECURITY AWARENESS',
                42 => 'V42_CLOUD_INADEQUATE PHYSICAL SECURITY PROCEDURES',
                43 => 'V43_CLOUD_LACK OF RESOURCE ISOLATION',
                44 => 'V44_CLOUD_USER DEPROVISIONING',
                45 => 'V45_CLOUD_ ENCRYPTION OF ARCHIVES AND DATA IN TRANSIT',
                46 => 'V46_CLOUD_DATA PORTABILITY',
                47 => 'V47_CLOUD_INTEROPERABILITY',
                48 => 'V48_CLOUD_VENDOR LOCK-IN',
                49 => 'V49_CLOUD_PROVIDER DUE DILIGENCE',
                50 => 'V50_CLOUD_CORPORATE CLOUD POLICY',
            ],
        ];
        if ( !empty($properties[$itemId]) ) {
            return $properties[$itemId];
        }
        return null;
    }
    public function serializeArray($array, $uniqid=null) 
    {
        $str = null;
        if ( !empty($array) ) {
            foreach ($array as $key => $value) {
                $str .= '{"layout":"wysiwyg","key":"'.$uniqid.$key.'","attributes":{"id":"'.$key.'","title":"'.$value.'"}},';
            }
            if ( $str ) $str = '['. rtrim($str, ',') .']';
        }
        return $str;
    }
}